# kubectl apply -f fluentd-configmap.yaml
# kubectl delete pod -n kube-system -l k8s-app=fluentd-logging

apiVersion: v1
kind: ConfigMap
metadata:
  name: fluentd-config
  namespace: kube-system
data:
  fluent.conf: |
    # 입력 설정 (Input)
    <source>
      @type tail
      path /var/log/containers/aip-*.log  # 'aip' 네임스페이스의 로그만 수집
      pos_file /var/log/fluentd/fluentd-containers-aip.log.pos  # pos_file 경로
      tag kube.aip.*
      <parse>
        @type multi_format
        <pattern>
          format json
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </source>

    # Source for tailing syslog
    <source>
      @type tail
      tag k8s_node_syslog
      path /var/log/syslog
      pos_file /var/log/fluentd/fluentd-syslog.pos  # pos_file 경로
      <parse>
        @type syslog
        time_format %b %d %H:%M:%S
      </parse>
    </source>

    # 필터 설정 (Filter)
    <filter k8s_node_syslog>
      @type record_transformer
      enable_ruby true
      <record>
        timestamp ${Time.now.getlocal('+09:00').strftime('%Y-%m-%dT%H:%M:%S%z')}  # '@timestamp'를 'timestamp'로 변경
      </record>
    </filter>
    
    <filter kube.aip.*>
      @type parser
      key_name log
      reserve_data true
      <parse>
        @type multi_format
        <pattern>
          format json
        </pattern>
        <pattern>
          format none
        </pattern>
      </parse>
    </filter>

    # Kubernetes 메타데이터 필터 설정
    # 이 필터는 kube로 시작하는 모든 로그 태그에 대해 적용되며,
    # 각 로그에 Kubernetes 관련 메타데이터(네임스페이스, Pod 이름, 컨테이너 이름 등)를 추가합니다.
    # 이를 통해 로그의 출처를 명확히 하고, Kubernetes 환경에서 로그를 보다 쉽게 관리하고 분석할 수 있습니다.
    <filter kube.**>
      @type kubernetes_metadata
    </filter>

    # 출력 설정 (Output)
    <match **>
      @type elasticsearch        
      hosts "elasticsearch-master.efk.svc.cluster.local:9200"  # 수정된 Elasticsearch Host
      logstash_format true
      logstash_prefix "fluentd-aip-dev"  # 인덱스 패턴 수정

      # 버퍼 설정
      buffer_chunk_limit 16M  # 각 청크의 크기 제한
      buffer_queue_limit 512  # 버퍼 큐의 크기 제한
      flush_interval 3s  # 로그를 전송하는 주기
      retry_max_interval 60  # 재시도 최대 간격
      retry_forever true  # 영구적으로 재시도
      slow_flush_log_threshold 10s  # 플러시가 느리게 동작할 때 경고를 출력하는 임계값

    </match>
